"""Discover KiwiHouseSitters state, region, and subregion filter IDs.

This is an operator script, not production scraper code. It follows the site's
progressive search filter UI:

1. GET the base search page to discover state options.
2. POST each state to discover regions.
3. POST each region to discover subregions.
4. Write a markdown map for human review.
"""

from __future__ import annotations

import re
import unicodedata
from argparse import ArgumentParser, Namespace
from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

import requests
from bs4 import BeautifulSoup, Tag

from pet_sitting_palantir.kiwihousesitters.constants import (
    DEFAULT_TIMEOUT_SECONDS,
    DEFAULT_USER_AGENT,
    SEARCH_URL,
)
from pet_sitting_palantir.kiwihousesitters.search_filters import DEFAULT_SEARCH_FORM

DEFAULT_OUTPUT_PATH = (
    Path(__file__).parents[1]
    / "src"
    / "pet_sitting_palantir"
    / "kiwihousesitters"
    / "LOCATION_MAP.md"
)

REFINE_ACTION_PATTERN = re.compile(
    r"refineSearchAction\(this,'(?P<field>[^']+)','(?P<value>[^']+)'"
)


@dataclass(frozen=True)
class LocationOption:
    """One site filter option."""

    label: str
    slug: str
    value: str


@dataclass(frozen=True)
class RegionOption(LocationOption):
    """One region with discovered subregions."""

    subregions: tuple[LocationOption, ...] = field(default_factory=tuple)


@dataclass(frozen=True)
class StateOption(LocationOption):
    """One state/island with discovered regions."""

    regions: tuple[RegionOption, ...] = field(default_factory=tuple)


def main() -> int:
    """Run location discovery."""
    args = _parse_args()
    states = discover_location_map()
    args.output.write_text(render_markdown(states), encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


def discover_location_map() -> tuple[StateOption, ...]:
    """Discover the state/region/subregion hierarchy from live site HTML."""
    with requests.Session() as session:
        session.headers.update(
            {
                "User-Agent": DEFAULT_USER_AGENT,
                "Referer": SEARCH_URL,
            }
        )

        base_html = _get_search_page(session)
        states = _extract_options(base_html, field_name="state")

        discovered_states: list[StateOption] = []
        for state in states:
            region_html = _post_search_form(session, {"state": state.value})
            regions = _extract_options(region_html, field_name="region")

            discovered_regions: list[RegionOption] = []
            for region in regions:
                subregion_html = _post_search_form(
                    session,
                    {
                        "state": state.value,
                        "region": region.value,
                    },
                )
                subregions = _extract_options(subregion_html, field_name="subregion")
                discovered_regions.append(
                    RegionOption(
                        label=region.label,
                        slug=region.slug,
                        value=region.value,
                        subregions=tuple(subregions),
                    )
                )

            discovered_states.append(
                StateOption(
                    label=state.label,
                    slug=state.slug,
                    value=state.value,
                    regions=tuple(discovered_regions),
                )
            )

        return tuple(discovered_states)


def render_markdown(states: Iterable[StateOption]) -> str:
    """Render discovered location filters as markdown tables."""
    generated_at = datetime.now(tz=UTC).isoformat(timespec="seconds")
    lines = [
        "# KiwiHouseSitters Location Filter Map",
        "",
        "Generated by `discovery/discover_kiwihousesitters_locations.py`.",
        "",
        f"Generated at: `{generated_at}`",
        "",
        "This is a human-reviewed map of the site's state, region, and subregion filter IDs.",
        "Production code should keep database `site_filter` values readable and translate them",
        "to these site IDs at the KiwiHouseSitters adapter boundary.",
        "",
        "## States",
        "",
        "| Label | Stored slug/value | Site field |",
        "| --- | --- | --- |",
    ]

    states = tuple(states)
    for state in states:
        lines.append(f"| {state.label} | `{state.value}` | `state` |")

    for state in states:
        lines.extend(
            [
                "",
                f"## {state.label} Regions",
                "",
                "| Label | Suggested stored slug | Site region ID |",
                "| --- | --- | ---: |",
            ]
        )
        for region in state.regions:
            lines.append(f"| {region.label} | `{region.slug}` | `{region.value}` |")

        for region in state.regions:
            if not region.subregions:
                continue

            lines.extend(
                [
                    "",
                    f"### {region.label} Subregions",
                    "",
                    "| Label | Suggested stored slug | Site subregion ID |",
                    "| --- | --- | ---: |",
                ]
            )
            for subregion in region.subregions:
                lines.append(
                    f"| {subregion.label} | `{subregion.slug}` | `{subregion.value}` |"
                )

    return "\n".join(lines) + "\n"


def _parse_args() -> Namespace:
    parser = ArgumentParser(description="Discover KiwiHouseSitters location filter IDs.")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Markdown file to write.",
    )
    return parser.parse_args()


def _get_search_page(session: requests.Session) -> str:
    response = session.get(SEARCH_URL, timeout=DEFAULT_TIMEOUT_SECONDS)
    response.raise_for_status()
    return response.text


def _post_search_form(session: requests.Session, values: Mapping[str, str]) -> str:
    form_data = dict(DEFAULT_SEARCH_FORM)
    form_data.update(values)

    response = session.post(SEARCH_URL, data=form_data, timeout=DEFAULT_TIMEOUT_SECONDS)
    response.raise_for_status()
    return response.text


def _extract_options(html: str, *, field_name: str) -> tuple[LocationOption, ...]:
    soup = BeautifulSoup(html, "html.parser")
    options: list[LocationOption] = []

    for link in soup.select("#location-options a[onclick*='refineSearchAction']"):
        option = _option_from_link(link)
        if option is None or option[0] != field_name:
            continue

        _, value, label = option
        options.append(
            LocationOption(
                label=label,
                slug=_slugify(label),
                value=value,
            )
        )

    return tuple(options)


def _option_from_link(link: Tag) -> tuple[str, str, str] | None:
    onclick = link.get("onclick", "")
    match = REFINE_ACTION_PATTERN.search(onclick)
    if not match:
        return None

    label = link.get_text(" ", strip=True)
    return match.group("field"), match.group("value"), label


def _slugify(label: str) -> str:
    normalized = unicodedata.normalize("NFKD", label)
    ascii_label = normalized.encode("ascii", "ignore").decode("ascii")
    slug = ascii_label.lower()
    slug = slug.replace("'", "")
    slug = slug.replace("&", " and ")
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")


if __name__ == "__main__":
    raise SystemExit(main())
